### ISSUE TITLE
Does not work with single language

### ISSUE THREAD

**Issue by crtl** [willdurand/Negotiation#102] opened 2019-08-26 09:39 UTC
When youve only selected a single language in your browser (I tried it in Firefox 68) the library will not detect the language.
The header sent is:
```
Accept-Language: de-DE
```

**Comment by Marcin-TA** [comment] 2019-10-01 10:34
Did you find any another working library?

**Comment by Seb33300** [comment] 2019-10-18 14:22
Same issue here with `LanguageNegotiator`.

I have a computer where Edge return only:
```
Accept-Language: fr-FR
```
And
``` php
$negotiator->getBest('fr-FR', ['en', 'fr']); // returns NULL
```

**Comment by Seb33300** [comment] 2019-10-19 09:21
Just found out that the issue was already fixed on 2.x branch, but no new tag have been created since a while.

You need configure your composer.json to use the current 2.x branch to get the fix:
```
"willdurand/negotiation": "2.x-dev"
```

**Comment by emri99** [comment] 2020-08-12 13:13
This should be greatly appreciated to create a new release 2.3.2 with this fix (for PHP 5.x)
However, I haven't been able to find a fix for version related to PHP 7.x, did I miss something ?
Thanks ;)

**Comment by Seb33300** [comment] 2021-03-17 04:03
@willdurand I tested the new 3.0.0 tag but this issue is still here.

This can be easily reproduced with:
``` php
$negotiator = new \Negotiation\LanguageNegotiator();
$bestLanguage = $negotiator->getBest('fr-FR', ['en', 'fr']); // returns NULL
```

When using `"willdurand/negotiation": "2.x-dev"`, it works as expected:
``` php
$negotiator = new \Negotiation\LanguageNegotiator();
$bestLanguage = $negotiator->getBest('fr-FR', ['en', 'fr']); // returns fr
```

it looks like one fix applied to `2.x-dev` was not properly merged into `3.0`

**Comment by willdurand** [comment] 2021-03-17 07:38
> it looks like one fix applied to `2.x-dev` was not properly merged into `3.0`

mm interesting, maybe I should have merge `2.x` into `master` before releasing `3.0`. I thought those branches were in sync already.

**Comment by Seb33300** [comment] 2021-03-17 07:40
I didn't try it but #113 looks to be the missing fix

**Comment by willdurand** [comment] 2021-03-17 07:42
I'll take a look this week.

**Comment by Seb33300** [comment] 2021-05-13 07:57
Hello @willdurand, any news on this?

**Comment by willdurand** [comment] 2022-01-30 19:47
should be fixed by https://github.com/willdurand/Negotiation/pull/113, I am sorry that this took almost a year.

**Closed by willdurand** 2022-01-30 19:47 UTC
